services:
  findex:
    build: .
    image: findex
    restart: unless-stopped
    container_name: findex
    working_dir: /data
    ports:
      - 3000:3000
    volumes:
      - /home/yonatan/test:/data/node1:ro
      - /home/yonatan/pkg:/data/node2:ro
    env_file: .env
